test 7

diff --git a/.github/workflows/add-priority.yml b/.github/workflows/add-priority.yml
--- a/.github/workflows/add-priority.yml
+++ b/.github/workflows/add-priority.yml
@@ -16,7 +16,7 @@ jobs:
 
       - name: Validate Secrets
         run: |
-          if [ -z "${{ secrets.JIRA_USERNAME }}" ]; then echo "Missing JIRA_USERNAME"; exit 1; fi
+          if [ -z "${{ secrets.BASIC_AUTH_TOKEN }}" ]; then echo "Missing JIRA_USERNAME"; exit 1; fi
           if [ -z "${{ secrets.JIRA_API_TOKEN }}" ]; then echo "Missing JIRA_API_TOKEN"; exit 1; fi
           if [ -z "${{ secrets.JIRA_BASE_URL }}" ]; then echo "Missing JIRA_BASE_URL"; exit 1; fi
           echo "All required secrets are set."
